### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by samtech09** [fordnn/usersexportimport#1]
How to Import / Export links are broken.

Can it be used to migrate users from DNN 7.0 to 9.2

**Comment by fordnn** [comment]
Hi! Thank you for your question!

For DNN 7.x please use PA 01.01.05 https://github.com/fordnn/usersexportimport/tree/master/Install

For DNN 9.x please use recent PA 01.01.07 https://github.com/fordnn/usersexportimport/releases

Please write us if you have any questions - will be glad to help!
