### ISSUE TITLE
Index out of range while importing users

### ISSUE THREAD

**Issue by Navilois** [fordnn/usersexportimport#11]
Unfortunately the most recent update did not fix the issue #6 

DNN: 9.8.1
forDNN.UsersExportImport: 1.2.5 (both export and import)

Screenshot:
![fordnnimportbug](https://user-images.githubusercontent.com/55184952/115189450-c00e0a80-a0e6-11eb-998a-98350c1a8c93.jpg)

Error log:
04/19/2021 08:04:28
General Exception
AbsoluteURL /API/forDNN.UsersExportImport/ExportImport/DoImport DefaultDat 
AbsoluteURL:/API/forDNN.UsersExportImport/ExportImport/DoImport
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:6b68e970-5e7c-4e55-bc1a-2c323c9c15e9

AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:OAshO4Zx8RRI3qEaXaJJdir8eAU=

Message:Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

StackTrace:
   at System.Collections.ArrayList.get_Item(Int32 index)
   at forDNN.Modules.UsersExportImport.CommonController.CSV2Table(Byte[] lstBytes)

InnerMessage:
InnerStackTrace:
Source:mscorlib
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name:

**Comment by fordnn** [comment]
Dear Alois,

Thank you very much for this info!

It looks like there is an issue with CSV. Can you please send us to support [at] fordnn com CSV file with at least 1 line of data (might be dummy).

Best regards,
Serg

**Comment by fordnn** [comment]
Sorry, I mean with any lines, generated an issue (for example 487, 4293, etc)

**Comment by Navilois** [comment]
I'm not sure if the line number refers to the actual line number or the UserID. Anyways I sent a few sample lines, one of them should be 487 ;)

Maybe this issue is related to issue #12, since the password column should be unexpected?

**Comment by fordnn** [comment]
Dear Alois,

We published PA 01.02.06 with fix for this issue. Thank you for your help with it!

One comment about CSV you sent us for testing: it seems each line in it contains " char at the start and end of the line, what is not common CSV standard. Can you please follow example of the CSV, provided in the module or just export as example.

Please let us know if there are any more questions or comments.

Best regards,
Serg
