### ISSUE TITLE
Order of columns in export

### ISSUE THREAD

**Issue by puresystems** [fordnn/usersexportimport#14]
Hi,

Would it be possible to set the order of the columns in the export to match the order of the profile fields set in DNN?

Thanks.

**Comment by fordnn** [comment]
Hi Dan,

Thank you for your request. We will include this into the next release.

Best regards,
Serg

**Comment by fordnn** [comment]
Hi Dan,

This change has been included into the PA 01.02.07.

Best regards,
Serg
