### ISSUE TITLE
Export of Country profile field issue

### ISSUE THREAD

**Issue by puresystems** [fordnn/usersexportimport#15]
Hi,

When exporting profile fields of type Country (which is a DNN list), it exports the list item ID's instead of the Country names. Can this be set to use the names instead?

Thanks.

**Comment by fordnn** [comment]
Hi Dan,

Thank you for your request. We will include this into the next release.

Best regards,
Serg

**Comment by fordnn** [comment]
Hi Dan,

This feature already available with PA 01.02.07.

It automatically detects is Profile Property a "List" type and creates additional column, like "Country_Text" or "Region_Text" with text value for it.

Best regards,
Serg

**Comment by puresystems** [comment]
Hi Serg, thanks for the update. We've just tested this aspect, and for the builtin Country profile field, the csv export does indeed contain a new column after the Country column called Country_Text which is good. But for the other newly created Country profile fields, the Text version isn't in the CSV.

**Comment by fordnn** [comment]
Hi Dan,

Can you please describe what exact Property Profiles you have: name and type. It should allow me to recreate issue locally.

Thanks in advance!

Best regards,
Serg

**Comment by puresystems** [comment]
Hi Serg,

The type of the field is Country and we've named it "PostalDeliveryCountry". I've attached a screenshot for reference.

Thanks
Dan
![Screenshot 2021-12-14 131643](https://user-images.githubusercontent.com/4923523/146006562-0b321833-d94d-4130-a05c-c4c07fb1ebd6.png)

**Comment by fordnn** [comment]
Hi Dan,

We will try to reproduce it and to inform you.

Best regards,
Serg

**Comment by fordnn** [comment]
Hi Dan,

Issue with multiple properties of the same type has been fixed. Please try PA 01.02.08 release.

Best regards,
Serg

**Comment by puresystems** [comment]
Thanks Serg.
