### ISSUE TITLE
Exclude deleted Profile Properties

### ISSUE THREAD

**Issue by Timo-Breumelhof** [fordnn/usersexportimport#18]
After an export of Users I noticed that deleted profile properties are also included in the export list.
IMO it would be better to exclude those?

Reproduce:

Create a Profile property X
Delete the Profile property

Do an export of users, see the X property in the list

**Comment by fordnn** [comment]
Thank you, Timo! Will fix this.

**Comment by Timo-Breumelhof** [comment]
Thank you :-)

**Comment by fordnn** [comment]
Fixed in PA 01.02.09

**Comment by Timo-Breumelhof** [comment]
> Fixed in PA 01.02.09

Cool, thanks a lot!
