### ISSUE TITLE
Error when importing and not importing roles

### ISSUE THREAD

**Issue by perezandres** [fordnn/usersexportimport#3]
When trying to import a file, into DNN 9.6.1, that I have exported from DNN 8.0.4, I get an error for each record, and the roles aren't imported. Rest of data are imported correctly.
I've attached two screen captures, to show parameters and result.
![Anotación 2020-06-16 101612](https://user-images.githubusercontent.com/6237180/85048210-4b4f0480-b193-11ea-8cc6-5a42de858e06.png)
![Anotación 2020-06-16 101634](https://user-images.githubusercontent.com/6237180/85048222-4ee28b80-b193-11ea-9171-ae23071e7bee.png)

**Comment by fordnn** [comment]
Hi Francisco,

Sorry for this issue. Module does not create roles automatically. It just tries to find it by RoleID or by RoleName in system and to assign to user.

Would you like to add feature to automatically create Role on import?

Best, Serg

**Comment by perezandres** [comment]
Hi Serg,

Thank you for the explanation. I'll create the roles (they're few) and try again.
Automatic creation of roles could be a nice feature, of course, but I don't really need it currently ;-)
I'll let you know the result of my try.

I hope you're well.
Best regards,
Francisco

**Comment by perezandres** [comment]
Hi again, Serg,

I've been able to succesfully import al my users and their roles. Just a remark: I guess that the destination web must have all the same roles (by names) that we're trying to import; otherwise, roles import will fail and only users accounts will be created.

Best,
Francisco

**Comment by fordnn** [comment]
Thank you very much for update, Francisco!

Your description is clear. I will add new feature "Auto create roles on import" in the next release.

Wish you all the best,
Serg

**Comment by fordnn** [comment]
Hello Francisco,

FYI: just published new version of module 01.02.01 with functionality you asked.

Best regards,
Serg

**Comment by perezandres** [comment]
Thank you, Sergey.
I'll test it as soon as I can, although I don't need it currently ;-)

Best,
Francisco

**Comment by perezandres** [comment]
First try. Same error as before. User accounts get created but no roles at all. DNN 9.6.1.
![image](https://user-images.githubusercontent.com/6237180/86380252-35117000-bc8c-11ea-8ff3-90a25b8f07af.png)

**Comment by fordnn** [comment]
Francisco,
Sorry for this bug - can you please send me one line of your .csv to support [at] fordnn [dot] com? So I can debug.
Thanks in advance!
Serg

**Comment by fordnn** [comment]
Hi Francisco,

Did you have a chance to test recent release? Does issue still exist? If no - may we close it?

Best regards,
Serg

**Comment by perezandres** [comment]
Yes! I didn't get notified of yesterday's release, but I've just downloaded and installed it.
It took a little while to import 127 users but it seems as all user data were imported and, most important, roles were correctly added.
Great job, Serg!

Best regards,
Francisco
