### ISSUE TITLE
Issue with importing users - Doesnt update pre-existing accounts

### ISSUE THREAD

**Issue by kieran23101** [fordnn/usersexportimport#4]
Hi,

I would like to be able to export users, edit them in excel them re-import them so that i can save time (over 5000 user accounts)

Should this not be doing this already?

I thought it'd do this out the box

Regards
Kieran

**Comment by fordnn** [comment]
Dear Kieran,

Thank you for your request. 

You can use our Users Export/Import module for this task. Only recommendation for Import - better to split it by 1000 users to prevent timeout. For export no limitations.

Let us know if you have any other questions or comments.

Best regards,
Serg

**Comment by kieran23101** [comment]
Hi Serg,

Sorry, I'm not sure that you understood my question properly...

I have loads of account with lots of custom profile fields, we would like to export this data and edit it
When we re-import the spreadsheet we would like it to **update** the users / profiles on the site.

Does it do this out the box?

Regards

Kieran

**Comment by fordnn** [comment]
Dear Kieran,

Yes, It does this out the box.

Best regards,
Serg

**Comment by kieran23101** [comment]
Hi Serg,

It doesnt seem to be doing it for me...

Not updated a single field, it just wants to create a new user

Regards 

Kieran

**Comment by fordnn** [comment]
Kieran,

Sorry, my mistake, now I understand your request.

This functionality does not exist in current version. If you like we can add this functionality - please contact us support@fordnn.com and we will provide you possible options.

Best regards,
Serg

**Comment by kieran23101** [comment]
Hi Serg,

No worries!

Have sent you an email...

Regards

Kieran Corkin

**Comment by kieran23101** [comment]
Hi Serg,

I have noticed that there is an update method being used here. Has this change been implemented?

https://github.com/fordnn/usersexportimport/blob/master/Components/CommonController.cs#L387

Regards

Kieran

**Comment by fordnn** [comment]
Hi Kieran,

Thank you for your question. Work on requested feature is in progress yet.

Best regards,
Serg

**Comment by fordnn** [comment]
Dear Kieran,

Requested feature added to the recent release.

Best regards,
Serg

**Comment by kieran23101** [comment]
Hi Serg,

I have had a look at the functionality that you have added however it looks like this only updates default dnn profile properties however it does not update custom profile properties which was included in the initial request...

Regards

Kieran

**Comment by fordnn** [comment]
Hi Kieran,

Thank you for feedback. We will include addon into the next release.

Best regards,
Serg

**Comment by kieran23101** [comment]
Hi Serg,

I was wondering how long it would be until this addon is added?

How often do you usually push new releases out?

This is so i can gauge expectations

Regards

Kieran Corkin

**Comment by fordnn** [comment]
Dear Kieran,

Thank you for your question.

We do not have tight deadlines on this module. We have your request in tasks list. Usually it takes 4-5 weeks from the request date.

Best regards,
Serg

**Comment by fordnn** [comment]
Dear Kieran,

We have just released PA 01.02.04. It should fix an issue with Custom Profiles updating.

Best regards,
Serg
