### ISSUE TITLE
Export by Selected Role

### ISSUE THREAD

**Issue by JoeAucoin** [fordnn/usersexportimport#5]
It would be great if you could export by a selected Role. Would you consider adding?

**Comment by fordnn** [comment]
Dear JoeAucoin,

Thank you for suggestion! We willl include this feature into the one of the next releases.

Best regards, Serg

**Comment by JoeAucoin** [comment]
excellent . . . thanks

**Comment by fordnn** [comment]
Dear JoeAucoin,

I would like to let you know PA 01.02.05 is ready to use with function "Export By Role".

Best regards, Serg
