### ISSUE TITLE
Index out of range exception

### ISSUE THREAD

**Issue by Navilois** [fordnn/usersexportimport#6]
Importing users throws an exception for every (new?) user:

[D:9][T:56][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at forDNN.Modules.UsersExportImport.CommonController.CSV2Table(Byte[] lstBytes)

Import settings:
- Import roles by RoleID from the "RoleIDs" column
- Import profile properties
- Create missed profile properties

I've used v1.1.7 of this module for a long time and just updated to 1.2.4. I tested import with the same data & settings for every version from 1.1.7 to 1.2.4. Only the most recent version throws this exception.
User data has been exported using 1.2.4 as well.

Installation:
DNN v9.8.1
forDnn.UsersExportImport v1.2.4

**Comment by fordnn** [comment]
Dear Navilois,

Thank you very much for this information. We are going to fix this bug and to produce new release asap.

Best regards,
Serg

**Comment by fordnn** [comment]
Dear Navilois,

I would like to inform you PA 01.02.05 is ready to use with bug fixes and support for DNN 9.8.1.

Best regards,
Serg
