### ISSUE TITLE
how to import User Images

### ISSUE THREAD

**Issue by azarbara** [fordnn/usersexportimport#7]
Could you please tell me how can import user avatar with csv file?

**Comment by fordnn** [comment]
Dear Mohammad Azarbara,

To import or update users avatar all you need is just to have a column "Photo" in your CSV file. In this column you can put FileID of the image you would like to use as avatar. That's it.

Please let us know if you have any more questions.

Best regards, Serg

**Comment by azarbara** [comment]
Thanks Serg, 
I have couple of users avatar in a file in site assets (portals/0/user-avatars)
hove can create a relation between this avatars and CSV file, where I can create FileID of this avatars to put in CSV file.
Thanks again

**Comment by fordnn** [comment]
Dear Mohammad,

You can find FileID in the "Files" table in the database. There is column "FileID". You can get it here and put into CSV file.

Best regards, Serg

**Comment by azarbara** [comment]
OK Thank you so much
