### ISSUE TITLE
Kills the object

### ISSUE THREAD

**Issue by jdomian** [fordnn/usersexportimport#8]
https://github.com/fordnn/usersexportimport/blob/705cff39d2f8b146aba1b3e0aad8776bb723212b/Components/CommonController.cs#L313

This I found killed the object if "UpdateExisting" was checked. Then it would error on objUser.Profile.InitialiseProfile() as the Profile property would no longer exist.

**Comment by fordnn** [comment]
Dear Jonathan,

Thank you very much for this info. We will fix this issue and will add new release for it.

Best regards, Serg

**Comment by fordnn** [comment]
Dear Jonathan,

We have just published PA 01.02.06 with fix for this issue.

Best regards,
Serg
