### ISSUE TITLE
Support Unicode characters

### ISSUE THREAD

**Issue by azarbara** [fordnn/usersexportimport#9]
I have a test for import data from CSV file with Persian characters like 'نام'
after successful import this characters convert to ??? in database, 
could you please check and fix it?

**Comment by fordnn** [comment]
Dear Mohammad,

Thank you for this information.

Our module is in use in many languages and many websites. It uses UTF-8 encoding. I copied chars from your message and added into CSV file. File saved with UTF-8 encoding. Then I did an import and all chars were imported successfully (screenshot):

![image](https://user-images.githubusercontent.com/4679341/108488792-756c3f80-72a9-11eb-8018-1b688360d388.png)

Please double check your CSV file is saved with UTF-8 encoding and try again. If issue persists, then we would need and example of the CSV file for debugging (please send it to support@fordnn.com).

Best regards,
Serg
